#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')


height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1/10}')


weight=$(jq -r '.weight' data.json | awk '{printf "%.0f", $1/10}')

type=$(jq -r '.types[].type.name' data.json | sed 's/.*/\u&/' | awk '{types = types $0 " "} END {gsub(/ $/, "", types); print types}')

echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."